-- SQL Server Seed/Test Data Script
-- This script inserts realistic test data into the tables generated by your EF Core model.
-- Assumptions:
--   - Tables are already created via EF Core migrations (e.g., Patients, LabParameters, LabRequests, LabReports, Notifications).
--   - Enum values are stored as integers (default EF Core behavior):
--     - Gender: 0 = Male, 1 = Female
--     - BloodGroup: 0 = A_Positive, 1 = A_Negative, 2 = B_Positive, 3 = B_Negative, 4 = AB_Positive, 5 = AB_Negative, 6 = O_positive, 7 = O_negative
--     - LabRequestState: 0 = Pending, 1 = Completed
--   - LabParameter represents real medical tests (e.g., blood, urine, etc.)—I've used realistic examples like Hemoglobin (blood), Glucose (blood/urine), etc.
--   - Data is interconnected to satisfy relationships (e.g., LabRequests linked to Patients, Notifications to LabReports).
--   - Inserting ~5-10 records per table for a good test dataset.
--   - Run this in SQL Server Management Studio (SSMS) or via your DatabaseManagementService if adapted.

-- Disable FK checks temporarily to allow inserts in any order (optional, but helpful for seeding)
SET NOCOUNT ON;
ALTER TABLE [LabRequests] NOCHECK CONSTRAINT ALL;
ALTER TABLE [LabReports] NOCHECK CONSTRAINT ALL;
ALTER TABLE [Notifications] NOCHECK CONSTRAINT ALL;

-- 1. Insert into LabParameters (standalone table with realistic medical test parameters)
INSERT INTO [LabParameters] ([Name])
VALUES
    ('Hemoglobin'),          -- Blood test for oxygen-carrying capacity
    ('White Blood Cell Count'), -- Blood test for infection/inflammation
    ('Glucose'),             -- Blood/urine test for diabetes
    ('Cholesterol'),         -- Blood test for heart disease risk
    ('Creatinine'),          -- Blood/urine test for kidney function
    ('Urine pH'),            -- Urine test for acidity/alkalinity
    ('Bilirubin'),           -- Blood/urine test for liver function
    ('Platelet Count'),      -- Blood test for clotting
    ('Thyroid Stimulating Hormone (TSH)'), -- Blood test for thyroid function
    ('Vitamin D');           -- Blood test for bone health

-- 2. Insert into Patients (base table with realistic patient data)
INSERT INTO [Patients] ([Uid], [FirstName], [LastName], [DateOfBirth], [Gender], [BloodGroup])
VALUES
    ('UID-1001', 'John', 'Doe', '1985-06-15', 0, 0),  -- Male, A_Positive
    ('UID-1002', 'Jane', 'Smith', '1990-02-20', 1, 2), -- Female, B_Positive
    ('UID-1003', 'Michael', 'Johnson', '1975-11-30', 0, 4), -- Male, AB_Positive
    ('UID-1004', 'Emily', 'Davis', '2000-04-10', 1, 6), -- Female, O_positive
    ('UID-1005', 'David', 'Wilson', '1960-08-25', 0, 1), -- Male, A_Negative
    ('UID-1006', 'Sarah', 'Martinez', '1988-12-05', 1, 3), -- Female, B_Negative
    ('UID-1007', 'Robert', 'Anderson', '1995-07-18', 0, 5), -- Male, AB_Negative
    ('UID-1008', 'Linda', 'Taylor', '1972-03-12', 1, 7), -- Female, O_negative
    ('UID-1009', 'James', 'Thomas', '1982-09-22', 0, 0), -- Male, A_Positive
    ('UID-1010', 'Patricia', 'Hernandez', '1993-01-08', 1, 2); -- Female, B_Positive

-- 3. Insert into LabRequests (links to Patients, with realistic request states)
-- Assuming Patient IDs start from 1 (auto-generated IDENTITY)
INSERT INTO [LabRequests] ([Created], [LabRequestState], [PatientId])
VALUES
    ('2023-01-10 09:00:00', 1, 1),  -- Completed, for Patient 1 (blood test request)
    ('2023-02-15 10:30:00', 0, 2),  -- Pending, for Patient 2 (urine analysis)
    ('2023-03-20 11:45:00', 1, 3),  -- Completed, for Patient 3 (glucose check)
    ('2023-04-25 14:00:00', 0, 4),  -- Pending, for Patient 4 (cholesterol panel)
    ('2023-05-30 15:15:00', 1, 5),  -- Completed, for Patient 5 (kidney function)
    ('2023-06-05 08:45:00', 0, 6),  -- Pending, for Patient 6 (thyroid test)
    ('2023-07-10 12:00:00', 1, 7),  -- Completed, for Patient 7 (vitamin D level)
    ('2023-08-15 13:30:00', 0, 8),  -- Pending, for Patient 8 (liver function)
    ('2023-09-20 16:00:00', 1, 9),  -- Completed, for Patient 9 (platelet count)
    ('2023-10-25 17:45:00', 0, 10); -- Pending, for Patient 10 (white blood cell count)

-- 4. Insert into LabReports (links to Patients and optional LabRequests, with sample content)
-- Content is simplified text (e.g., results); in reality, this could be JSON or detailed reports.
INSERT INTO [LabReports] ([Content], [Created], [LabRequestId], [PatientId])
VALUES
    ('Hemoglobin: 14.5 g/dL (normal)', '2023-01-12 14:00:00', 1, 1),  -- Linked to Request 1, Patient 1
    ('Glucose: 95 mg/dL (normal)', '2023-02-17 15:30:00', NULL, 2),   -- No request, direct for Patient 2
    ('Cholesterol: 180 mg/dL (normal)', '2023-03-22 16:45:00', 3, 3), -- Linked to Request 3, Patient 3
    ('Creatinine: 1.0 mg/dL (normal)', '2023-04-27 09:00:00', 4, 4),  -- Linked to Request 4, Patient 4
    ('Urine pH: 6.5 (normal)', '2023-05-31 10:15:00', NULL, 5),       -- No request, Patient 5
    ('TSH: 2.5 mIU/L (normal)', '2023-06-07 11:30:00', 6, 6),         -- Linked to Request 6, Patient 6
    ('Vitamin D: 30 ng/mL (sufficient)', '2023-07-12 12:45:00', 7, 7),-- Linked to Request 7, Patient 7
    ('Bilirubin: 0.8 mg/dL (normal)', '2023-08-17 14:00:00', NULL, 8),-- No request, Patient 8
    ('Platelet Count: 250,000 /µL (normal)', '2023-09-22 15:15:00', 9, 9), -- Linked to Request 9, Patient 9
    ('White Blood Cell Count: 7,000 /µL (normal)', '2023-10-27 16:30:00', 10, 10); -- Linked to Request 10, Patient 10

-- 5. Insert into Notifications (links to LabReports, with realistic messages)
INSERT INTO [Notifications] ([Message], [LabReportId])
VALUES
    ('Lab report ready for review: Hemoglobin results available.', 1),  -- For Report 1
    ('Notification: Glucose test completed.', 2),                      -- For Report 2
    ('Alert: Cholesterol levels updated.', 3),                         -- For Report 3
    ('New results: Creatinine test processed.', 4),                    -- For Report 4
    ('Urine pH report is now available.', 5),                          -- For Report 5
    ('TSH results ready - please check.', 6),                          -- For Report 6
    ('Vitamin D deficiency check completed.', 7),                      -- For Report 7
    ('Bilirubin test results uploaded.', 8),                           -- For Report 8
    ('Platelet count report available.', 9),                           -- For Report 9
    ('White blood cell count results ready for review.', 10);          -- For Report 10

-- Re-enable FK checks
ALTER TABLE [LabRequests] CHECK CONSTRAINT ALL;
ALTER TABLE [LabReports] CHECK CONSTRAINT ALL;
ALTER TABLE [Notifications] CHECK CONSTRAINT ALL;

-- Optional: Verify inserts
SELECT * FROM [LabParameters];
SELECT * FROM [Patients];
SELECT * FROM [LabRequests];
SELECT * FROM [LabReports];
SELECT * FROM [Notifications];